### ISSUE TITLE
Update HTML/CSS to meet the Whole Washington Style Guide

### ISSUE THREAD

**Issue by dentemple** [marcaaron/ww-calc-2.0#11]
[Link to the Style Guide](https://drive.google.com/file/d/1jClPK0b_K8QV7CVnaAy5TGxj8iQq4DqN/view?usp=sharing)

I'm going to give this one a shot tonight and tomorrow and update as much as I can.

Definitely post here if there's anything I end up missing!

**Comment by marcaaron** [comment]
We should be good on the colors and font adjustments. Something to keep in mind is the media queries for the current header if that font is to change since there are quite a few that keep it consistent across devices. Another thing to consider is that there are fonts being used for the html2canvas invisible meme render image. So we might eventually have to change some of that up so we don't cause excessive load times, but maybe don't stress it for now.
