### ISSUE TITLE
Business Calculator - Results Display

### ISSUE THREAD

**Issue by couchpilotnye** [marcaaron/ww-calc-2.0#50]
The reds are different
The size of the bars are different
The savings bar is not centered
![image](https://user-images.githubusercontent.com/37560660/38450742-f6c571b8-39d7-11e8-9b3a-badf4ffc3113.png)

**Comment by marcaaron** [comment]
Besides the color mismatch. What's the issue here? 

The bars programmatically change size to help user's visualize the difference between what they're paying and what they will pay. It's essentially a two line chart. Thus, the savings bar is not supposed to be centered and their size will depend on a user's results.

**Comment by marcaaron** [comment]
An issue for this issue... if it's an issue... exists @ #41 
Going to close this issue.

**Comment by couchpilotnye** [comment]
I apologize. I didn’t realize it was intentional. 

 

Could be my personal interpretation and others will get it. Let’s keep it.
