### ISSUE TITLE
IE Bug - Stuck on 'Number of Adults' step

### ISSUE THREAD

**Issue by couchpilotnye** [marcaaron/ww-calc-2.0#67]
This in from a Volunteer:
On Internet Explorer it freezes up on the page that asks the number of adults over 19 years of age. You can input a value but the "NEXT" button does nothing. Neither does the forward arrow in the red band. It does not seem to function however the "back one" button does.

They provided this screenshot:
![alansissue](https://user-images.githubusercontent.com/37560660/38780233-284dcb52-4088-11e8-9451-020052af891e.jpg)

**Comment by marcaaron** [comment]
Hmm, I don't have access to IE, nor do I recommend anyone use that browser, like ever, since the compatibility with current development standards is very poor. We could go chasing down every IE bug, but alternatively we can maybe recommend that user's update their browsers at the start page.

My guess is what's happening here is that IE isn't recognizing that the form has been filled. The back arrow always works. But the app can't move forward via the top arrow or the bottom next button unless the forms are filled - this is to validate that the user has entered something and we won't be left with holes in our calculations. However, I have no idea why this is happening... 

Without windows dev environment I'm not sure I can get to the root of this issue right away. But perhaps someone familiar with IE compatibility can help?

**Comment by marcaaron** [comment]
This should be fixed now. We can reopen if people report this issue again.
